name: oya_ttt
description: "A Tic Tac Toe game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  oya_ttt_core:
    path: ../oya_ttt_core/
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_riverpod: ^3.0.3
  drift: ^2.23.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.3
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.23.0
  build_runner: ^2.4.13
  snaptest: ^0.2.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/character/
    - assets/avatar/

  fonts:
    - family: Tilt Warp
      fonts:
        - asset: assets/fonts/TiltWarp-Variable.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Variable.ttf
  shaders:
    - shaders/glitch.frag
