name: oya_ttt_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  dart_mappable: ^4.6.1

dev_dependencies:
  build_runner: ^2.10.1
  dart_mappable_builder: ^4.6.1
  lints: ^6.0.0
  test: ^1.25.6
